import Link from 'next/link'
import FAQItem from '@/components/tool/FAQItem'

export default function RawToJpgContentSection() {
  return (
    <section
      className="space-y-8 pt-8 border-t border-border"
      aria-label="Guide to converting RAW to JPG"
    >
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">What Is a Camera RAW File?</h2>
        <p className="text-text-muted text-sm leading-relaxed">
          A camera RAW file is the unprocessed sensor data captured by a digital camera before any
          in-camera processing is applied. Every major camera manufacturer uses a proprietary RAW
          format: Canon uses CR2 (older DSLRs) and CR3 (EOS R-series and newer), Nikon uses NEF,
          Sony uses ARW, Fujifilm uses RAF, and Panasonic uses RW2. Adobe DNG is an open RAW format
          used by some cameras directly and by Lightroom for archiving.
        </p>
        <p className="text-text-muted text-sm leading-relaxed">
          RAW files are significantly larger than JPGs — a 24-megapixel sensor produces a RAW file
          of roughly 25–35MB, versus 4–8MB for an equivalent JPG. They are prized by photographers
          because they preserve all the tonal information the sensor captured, allowing extensive
          post-processing adjustments to exposure, white balance, and color grading without quality
          loss. The trade-off is compatibility: RAW files do not open in standard image viewers,
          browsers, or most apps without dedicated software.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">Why Convert RAW to JPG?</h2>
        <p className="text-text-muted text-sm leading-relaxed">
          The most common reason to convert RAW to JPG is compatibility. A CR2 or NEF file cannot be
          uploaded to Instagram, emailed directly, viewed in Windows Photo Viewer without a codec,
          or sent to a photo printing service without first converting it. JPG opens everywhere, on
          every device, in every browser and app, with no software or plugins required.
        </p>
        <p className="text-text-muted text-sm leading-relaxed">
          Other common reasons include sharing photos quickly after a shoot, sending proofs to
          clients, backing up edited images, uploading to stock photo platforms, and submitting
          photos to websites or forms that only accept JPG or PNG.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">
          How This Converter Works — No Upload Required
        </h2>
        <p className="text-text-muted text-sm leading-relaxed">
          Almost every RAW file produced by modern cameras contains an embedded full-resolution JPEG
          preview. This preview is generated by the camera itself at the time of capture and stored
          inside the RAW container alongside the sensor data. When you shoot in RAW+JPEG mode or
          preview images on the camera&apos;s LCD screen, the camera is displaying this embedded
          preview.
        </p>
        <p className="text-text-muted text-sm leading-relaxed">
          This tool reads the RAW file directly in your browser, locates the largest embedded JPEG
          preview, and extracts it — without any server upload, without WASM decoders, and without
          demosaicing the raw sensor data. The extracted JPG is typically full-resolution and
          camera-quality because the camera&apos;s image processor created it at the moment of
          capture.
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-xs border-collapse mt-3">
            <thead>
              <tr className="bg-surface">
                <th className="text-left p-3 border border-border font-semibold text-text-main">
                  Format
                </th>
                <th className="text-left p-3 border border-border font-semibold text-text-main">
                  Camera brand
                </th>
                <th className="text-left p-3 border border-border font-semibold text-text-main">
                  Preview in RAW?
                </th>
              </tr>
            </thead>
            <tbody>
              {[
                ['CR2', 'Canon (older DSLRs)', 'Full-res JPEG — typical'],
                ['CR3', 'Canon (EOS R, newer)', 'Full-res JPEG — typical'],
                ['NEF', 'Nikon', 'Full-res JPEG — typical'],
                ['ARW', 'Sony', 'Full-res JPEG — typical'],
                ['DNG (camera)', 'Leica, Ricoh, others', 'Full-res JPEG — typical'],
                ['DNG (converted)', 'Lightroom archive', 'May vary — medium or full'],
                ['RAF', 'Fujifilm', 'Full-res JPEG — typical'],
                ['RW2', 'Panasonic', 'Full-res JPEG — typical'],
              ].map(([fmt, brand, preview]) => (
                <tr key={fmt} className="border-t border-border">
                  <td className="p-3 border border-border font-mono text-text-main">{fmt}</td>
                  <td className="p-3 border border-border text-text-muted">{brand}</td>
                  <td className="p-3 border border-border text-text-muted">{preview}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">
          How to Convert CR2, CR3, NEF, or ARW to JPG
        </h2>
        <ol className="space-y-3 text-sm text-text-muted list-decimal list-inside leading-relaxed">
          <li>
            <strong className="text-text-main">Upload your RAW file.</strong> Click the upload area
            or drag and drop your CR2, CR3, NEF, ARW, or DNG file. Files up to 100MB are supported —
            RAW files from high-resolution sensors (45MP, 61MP) can exceed 80MB.
          </li>
          <li>
            <strong className="text-text-main">Extraction runs automatically.</strong> The tool
            reads the RAW file structure, locates the largest embedded JPEG preview, and extracts it
            in your browser. No files are sent to any server. Extraction typically takes under one
            second regardless of RAW file size.
          </li>
          <li>
            <strong className="text-text-main">Download the JPG.</strong> Click Download to save the
            extracted JPG. The filename retains the original name with a .jpg extension.
          </li>
        </ol>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">RAW Extraction vs Full RAW Decoding</h2>
        <p className="text-text-muted text-sm leading-relaxed">
          True RAW decoding (demosaicing) processes the raw Bayer sensor data to reconstruct a
          full-color image, a computationally intensive step that professional software like Adobe
          Lightroom or DarkTable performs. This process applies tone curves, noise reduction,
          sharpening, and lens corrections that differ between software.
        </p>
        <p className="text-text-muted text-sm leading-relaxed">
          This tool uses preview extraction — a different and faster approach. The camera&apos;s own
          image processor already demosaiced the image and stored it as a JPEG inside the RAW file.
          This preview is identical to what the camera would produce if you had shot in JPG mode,
          including the camera&apos;s picture style, color profile, and noise reduction settings
          applied at capture. For most practical purposes (sharing, printing, uploading), this is
          indistinguishable from a full RAW decode.
        </p>
        <p className="text-text-muted text-sm leading-relaxed">
          The only scenario where extraction differs from a manual RAW edit is if you need to change
          the exposure significantly, pull details from extreme highlights or shadows, or apply a
          different color grading than the in-camera settings. In those cases, use Lightroom,
          DarkTable, Capture One, or RawTherapee to decode the RAW data directly.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">
          Privacy — Your Camera Files Never Leave Your Device
        </h2>
        <p className="text-text-muted text-sm leading-relaxed">
          RAW files from your camera contain EXIF metadata including GPS coordinates (if your camera
          records location), shooting date and time, camera model, lens model, and exposure
          settings. This tool runs entirely in your browser using JavaScript — the RAW file is read
          locally, the embedded JPEG is extracted locally, and the result is downloaded locally. No
          data is ever sent to a server, logged, or stored. This applies to every file you process.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">Which Camera Models Are Supported?</h2>
        <p className="text-text-muted text-sm leading-relaxed">
          The tool works with RAW files from all major camera families: Canon EOS R5, R6, R8, R50,
          R100 (CR3), Canon EOS 7D, 5D Mark III, 6D, Rebel T3i, T5i, T7i (CR2), Nikon Z6 II, Z8,
          D850, D750, D7500, D5600, D3500 (NEF), Sony Alpha A7 IV, A7R V, A7C II, A6700, ZV-E10
          (ARW), Fujifilm X-T5, X-S20, X100VI (RAF), and Panasonic Lumix GH6, G9 II, S5 II (RW2). In
          general, any camera produced after 2005 that embeds a full-resolution JPEG preview inside
          its RAW container — which is the default for virtually all modern cameras — will work
          correctly with this tool.
        </p>
      </div>

      <div className="space-y-3">
        <h2 className="text-xl font-bold text-text-main">More Free Image Tools</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm">
          {[
            { href: '/compress-image/', label: 'Compress Image' },
            { href: '/resize-image/', label: 'Resize Image' },
            { href: '/heic-to-jpg/', label: 'HEIC to JPG' },
            { href: '/compress-image-to-100kb/', label: 'Compress to 100KB' },
            { href: '/resize-image-in-kb/', label: 'Resize to KB' },
            { href: '/compress-image-for-instagram/', label: 'Compress for Instagram' },
          ].map((t) => (
            <Link
              key={t.href}
              href={t.href}
              className="rounded-lg border border-border px-3 py-2 text-text-main hover:border-primary hover:text-primary transition-colors text-center"
            >
              {t.label}
            </Link>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <h2 className="text-xl font-bold text-text-main">Frequently Asked Questions</h2>
        <div className="divide-y divide-border">
          {[
            {
              q: 'Can I convert CR2, CR3, NEF, and ARW files with this tool?',
              a: 'Yes. The tool supports CR2 and CR3 (Canon), NEF (Nikon), ARW (Sony), DNG (Adobe and others), RAF (Fujifilm), RW2 (Panasonic), and ORF (Olympus). These formats account for the large majority of camera RAW files in use.',
            },
            {
              q: 'Is my RAW file uploaded to a server?',
              a: "No. All processing happens entirely in your browser using JavaScript. The RAW file is read locally on your device. Nothing is ever sent over the network. This is verifiable: open your browser's network tab while using the tool — you will see zero file upload requests.",
            },
            {
              q: 'What quality will the output JPG be?',
              a: 'The extracted JPG is the preview JPEG that the camera itself generated at the time of capture. For most modern cameras, this preview is full-resolution and uses quality settings equivalent to JPG quality 90–95. The result is visually identical to shooting in JPG mode with the same camera settings.',
            },
            {
              q: 'Why is the extracted JPG smaller than the RAW file?',
              a: 'This is normal. A RAW file stores the uncompressed or lightly compressed sensor data — 12 or 14 bits per pixel across all channels — which is much larger than a JPG. The embedded JPG preview uses lossy compression optimized for file size. A 30MB CR3 typically yields a 6–10MB JPG.',
            },
            {
              q: 'Does the extracted JPG preserve EXIF metadata?',
              a: 'Yes. The embedded JPEG preview inside a RAW file retains EXIF metadata including camera model, lens, exposure settings, and GPS coordinates. The extracted file includes this metadata as-is.',
            },
            {
              q: 'What if the tool warns me about a "small embedded preview"?',
              a: 'Some RAW files — particularly DNG files converted by third-party apps, HDR photos from phones saved as DNG, or very old compact cameras — only embed a medium or small JPEG preview rather than a full-resolution one. If this happens, the tool will notify you with the extracted dimensions. For full-resolution output in this case, you would need desktop RAW software like Lightroom or DarkTable.',
            },
            {
              q: 'Can I convert multiple RAW files at once?',
              a: 'Currently the tool converts one file at a time. Each conversion takes under one second regardless of RAW file size, so processing multiple files sequentially is fast. Batch RAW conversion is on the roadmap.',
            },
            {
              q: 'Does this work on iPhone and Android?',
              a: 'Yes. The tool runs in any modern browser including Safari on iPhone and Chrome on Android. Note that transferring large RAW files (30–80MB) from a camera to a phone may require a card reader or cable. Once the file is accessible in the Files app or Gallery, you can upload it the same way as any other file.',
            },
          ].map(({ q, a }) => (
            <FAQItem key={q} question={q} answer={a} />
          ))}
        </div>
      </div>
    </section>
  )
}
